### ISSUE TITLE
US 02.03.01

### ISSUE THREAD

**Issue by Hetul-P** [CMPUT301W22T19/QrACutie#12] opened 2022-02-10 21:44 UTC
As a player, I want to be able to browse QR codes that I own.

### Acceptance Criteria ###
Features:
- Display all user-owned QR codes as a list
- List must be scrollable if amount of codes exceeds the size of window
- Each QR code in the list should be clickable, taking the user to the QR Code activity

Documentation and testing:
- Javadoc comments for all public methods.
- Javadoc comments for all classes, abstract classes, and interfaces.
- Javadoc comments at the top of all source code file.
- At least one JUnit test for each public method.
- Robotium Tests for any added/modified UI functionality in Activity or Fragment classes.

**Comment by Austin-T** [comment] 2022-03-09 19:31
User story is duplicate of US 01.02.01. Thus, I a closing it

**Closed by Austin-T** 2022-03-09 19:31 UTC
Labels: sp-1, low-risk, game-qr-codes
